### ISSUE TITLE
doesn't build on VS 2013

### ISSUE THREAD

**Issue by Bsidey** [srinudhulipalla/JsonToSQL#1]
SqlScript.cs

LINE 138: sb.AppendLine("INSERT INTO [{table.TableName}] ([{string.Join("], [", names.ToArray())}]) VALUES ({string.Join(", ", values.ToArray())})");
                

LINE 141:                sb.AppendLine("$SET IDENTITY_INSERT [{table.TableName}] OFF");
Invalid character $

Please advise how to fix

**Comment by srinudhulipalla** [comment]
In order to compile you need minimum C# 6.0 version. Please use visual studio 2015 or higher.
